version: "3.9"

services:
  adenzo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: adenzo_app
    restart: always
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
