type: node-next
ingress: true

allowed_networks:
  adenzo:
    - 197.248.216.187/32
    - 197.254.97.46/32
    - 197.248.201.151/32

env:
  - name: NODE_NEXT
    value: staging
  - name: NEXT_PUBLIC_API_BASE_URL
    value: "https://api.ecom.staging.roamtech.whitemire-technologies.com/api/"
